import * as functions from "firebase-functions";

export const getAtleticoPlayers = functions.https.onRequest(
  (request, response) => {
    const atleticoPlayers = [
      {
        name: "Jan Oblak",
        position: "Goalkeeper",
        overall: 88,
        pace: 50,
        shooting: 40,
        passing: 60,
        dribbling: 58,
        defending: 40,
        physical: 65,
      },
      {
        name: "Ivo Grbić",
        position: "Goalkeeper",
        overall: 77,
        pace: 48,
        shooting: 35,
        passing: 55,
        dribbling: 50,
        defending: 38,
        physical: 60,
      },
      {
        name: "José María Giménez",
        position: "Defender",
        overall: 84,
        pace: 70,
        shooting: 45,
        passing: 68,
        dribbling: 65,
        defending: 85,
        physical: 83,
      },
      {
        name: "Stefan Savić",
        position: "Defender",
        overall: 82,
        pace: 65,
        shooting: 42,
        passing: 65,
        dribbling: 62,
        defending: 83,
        physical: 80,
      },
      {
        name: "Mario Hermoso",
        position: "Defender",
        overall: 81,
        pace: 70,
        shooting: 50,
        passing: 70,
        dribbling: 65,
        defending: 80,
        physical: 78,
      },
      {
        name: "Nahuel Molina",
        position: "Defender",
        overall: 80,
        pace: 80,
        shooting: 55,
        passing: 70,
        dribbling: 72,
        defending: 78,
        physical: 76,
      },
      {
        name: "Reinildo Mandava",
        position: "Defender",
        overall: 79,
        pace: 76,
        shooting: 48,
        passing: 65,
        dribbling: 66,
        defending: 80,
        physical: 78,
      },
      {
        name: "Axel Witsel",
        position: "Midfielder",
        overall: 81,
        pace: 60,
        shooting: 70,
        passing: 78,
        dribbling: 75,
        defending: 77,
        physical: 76,
      },
      {
        name: "Rodrigo De Paul",
        position: "Midfielder",
        overall: 83,
        pace: 75,
        shooting: 75,
        passing: 80,
        dribbling: 82,
        defending: 72,
        physical: 78,
      },
      {
        name: "Koke",
        position: "Midfielder",
        overall: 84,
        pace: 68,
        shooting: 72,
        passing: 85,
        dribbling: 80,
        defending: 70,
        physical: 75,
      },
      {
        name: "Marcos Llorente",
        position: "Midfielder",
        overall: 85,
        pace: 88,
        shooting: 78,
        passing: 78,
        dribbling: 80,
        defending: 76,
        physical: 82,
      },
      {
        name: "Saúl Ñíguez",
        position: "Midfielder",
        overall: 80,
        pace: 70,
        shooting: 72,
        passing: 75,
        dribbling: 74,
        defending: 72,
        physical: 78,
      },
      {
        name: "Thomas Lemar",
        position: "Midfielder",
        overall: 81,
        pace: 78,
        shooting: 70,
        passing: 77,
        dribbling: 82,
        defending: 60,
        physical: 70,
      },
      {
        name: "Antoine Griezmann",
        position: "Forward",
        overall: 88,
        pace: 78,
        shooting: 86,
        passing: 84,
        dribbling: 86,
        defending: 60,
        physical: 76,
      },
      {
        name: "Álvaro Morata",
        position: "Forward",
        overall: 84,
        pace: 80,
        shooting: 82,
        passing: 70,
        dribbling: 78,
        defending: 45,
        physical: 80,
      },
      {
        name: "Memphis Depay",
        position: "Forward",
        overall: 83,
        pace: 82,
        shooting: 84,
        passing: 75,
        dribbling: 84,
        defending: 35,
        physical: 76,
      },
      {
        name: "Ángel Correa",
        position: "Forward",
        overall: 82,
        pace: 85,
        shooting: 80,
        passing: 74,
        dribbling: 84,
        defending: 38,
        physical: 70,
      },
      {
        name: "Samuel Lino",
        position: "Forward",
        overall: 80,
        pace: 87,
        shooting: 75,
        passing: 72,
        dribbling: 82,
        defending: 40,
        physical: 72,
      },
    ];

    response.json({data: {players: atleticoPlayers}});
  }
);
