import * as functions from "firebase-functions";

export const getChelseaPlayers = functions.https.onRequest(
  (request, response) => {
    const chelseaPlayers = [
      {
        name: "Robert Sánchez",
        position: "Goalkeeper",
        overall: 83,
        pace: 53,
        shooting: 40,
        passing: 72,
        dribbling: 60,
        defending: 45,
        physical: 70,
      },
      {
        name: "Thiago Silva",
        position: "Defender",
        overall: 85,
        pace: 60,
        shooting: 50,
        passing: 78,
        dribbling: 65,
        defending: 88,
        physical: 78,
      },
      {
        name: "Reece James",
        position: "Defender",
        overall: 85,
        pace: 83,
        shooting: 70,
        passing: 80,
        dribbling: 80,
        defending: 82,
        physical: 82,
      },
      {
        name: "Ben Chilwell",
        position: "Defender",
        overall: 83,
        pace: 80,
        shooting: 65,
        passing: 76,
        dribbling: 74,
        defending: 80,
        physical: 78,
      },
      {
        name: "Enzo Fernández",
        position: "Midfielder",
        overall: 84,
        pace: 75,
        shooting: 76,
        passing: 86,
        dribbling: 80,
        defending: 74,
        physical: 76,
      },
      {
        name: "Conor Gallagher",
        position: "Midfielder",
        overall: 82,
        pace: 78,
        shooting: 72,
        passing: 78,
        dribbling: 75,
        defending: 72,
        physical: 78,
      },
      {
        name: "Raheem Sterling",
        position: "Forward",
        overall: 85,
        pace: 90,
        shooting: 82,
        passing: 78,
        dribbling: 86,
        defending: 40,
        physical: 70,
      },
      {
        name: "Christopher Nkunku",
        position: "Forward",
        overall: 86,
        pace: 88,
        shooting: 85,
        passing: 80,
        dribbling: 88,
        defending: 45,
        physical: 75,
      },
      {
        name: "Nicolas Jackson",
        position: "Forward",
        overall: 83,
        pace: 86,
        shooting: 80,
        passing: 74,
        dribbling: 82,
        defending: 42,
        physical: 78,
      },
    ];

    response.json({data: {players: chelseaPlayers}});
  }
);
