import * as functions from "firebase-functions";

export const getLiverpoolPlayers = functions.https.onRequest(
  (request, response) => {
    const liverpoolPlayers = [
      {
        name: "Alisson Becker",
        position: "Goalkeeper",
        overall: 89,
        pace: 55,
        shooting: 40,
        passing: 80,
        dribbling: 60,
        defending: 45,
        physical: 70,
      },
      {
        name: "Virgil van Dijk",
        position: "Defender",
        overall: 89,
        pace: 70,
        shooting: 55,
        passing: 75,
        dribbling: 70,
        defending: 91,
        physical: 88,
      },
      {
        name: "Trent Alexander-Arnold",
        position: "Defender",
        overall: 87,
        pace: 80,
        shooting: 70,
        passing: 90,
        dribbling: 82,
        defending: 75,
        physical: 75,
      },
      {
        name: "Andy Robertson",
        position: "Defender",
        overall: 86,
        pace: 85,
        shooting: 65,
        passing: 82,
        dribbling: 78,
        defending: 80,
        physical: 78,
      },
      {
        name: "Thiago Alcântara",
        position: "Midfielder",
        overall: 86,
        pace: 70,
        shooting: 78,
        passing: 88,
        dribbling: 85,
        defending: 65,
        physical: 70,
      },
      {
        name: "Alexis Mac Allister",
        position: "Midfielder",
        overall: 84,
        pace: 72,
        shooting: 80,
        passing: 85,
        dribbling: 82,
        defending: 68,
        physical: 74,
      },
      {
        name: "Mohamed Salah",
        position: "Forward",
        overall: 90,
        pace: 92,
        shooting: 88,
        passing: 80,
        dribbling: 90,
        defending: 45,
        physical: 75,
      },
      {
        name: "Darwin Núñez",
        position: "Forward",
        overall: 84,
        pace: 87,
        shooting: 82,
        passing: 72,
        dribbling: 80,
        defending: 40,
        physical: 80,
      },
      {
        name: "Luis Díaz",
        position: "Forward",
        overall: 85,
        pace: 89,
        shooting: 80,
        passing: 78,
        dribbling: 86,
        defending: 42,
        physical: 76,
      },
    ];

    response.json({data: {players: liverpoolPlayers}});
  }
);
