import * as functions from "firebase-functions";

export const getMadridPlayers = functions.https.onRequest(
  (request, response) => {
    const madridPlayers = [
      {
        name: "Thibaut Courtois",
        position: "Goalkeeper",
        overall: 90,
        pace: 52,
        shooting: 38,
        passing: 60,
        dribbling: 58,
        defending: 45,
        physical: 60,
      },
      {
        name: "Andriy Lunin",
        position: "Goalkeeper",
        overall: 82,
        pace: 50,
        shooting: 35,
        passing: 55,
        dribbling: 55,
        defending: 40,
        physical: 58,
      },
      {
        name: "Dani Carvajal",
        position: "Defender",
        overall: 84,
        pace: 75,
        shooting: 60,
        passing: 75,
        dribbling: 72,
        defending: 82,
        physical: 78,
      },
      {
        name: "Éder Militão",
        position: "Defender",
        overall: 86,
        pace: 78,
        shooting: 48,
        passing: 70,
        dribbling: 65,
        defending: 85,
        physical: 84,
      },
      {
        name: "David Alaba",
        position: "Defender",
        overall: 85,
        pace: 76,
        shooting: 65,
        passing: 80,
        dribbling: 78,
        defending: 82,
        physical: 80,
      },
      {
        name: "Antonio Rüdiger",
        position: "Defender",
        overall: 86,
        pace: 80,
        shooting: 50,
        passing: 70,
        dribbling: 65,
        defending: 86,
        physical: 88,
      },
      {
        name: "Ferland Mendy",
        position: "Defender",
        overall: 83,
        pace: 85,
        shooting: 60,
        passing: 75,
        dribbling: 78,
        defending: 80,
        physical: 82,
      },
      {
        name: "Aurélien Tchouaméni",
        position: "Midfielder",
        overall: 84,
        pace: 70,
        shooting: 68,
        passing: 78,
        dribbling: 75,
        defending: 82,
        physical: 85,
      },
      {
        name: "Luka Modrić",
        position: "Midfielder",
        overall: 87,
        pace: 68,
        shooting: 78,
        passing: 90,
        dribbling: 88,
        defending: 70,
        physical: 70,
      },
      {
        name: "Toni Kroos",
        position: "Midfielder",
        overall: 86,
        pace: 60,
        shooting: 82,
        passing: 92,
        dribbling: 82,
        defending: 68,
        physical: 72,
      },
      {
        name: "Eduardo Camavinga",
        position: "Midfielder",
        overall: 83,
        pace: 76,
        shooting: 70,
        passing: 78,
        dribbling: 80,
        defending: 78,
        physical: 80,
      },
      {
        name: "Jude Bellingham",
        position: "Midfielder",
        overall: 87,
        pace: 78,
        shooting: 85,
        passing: 82,
        dribbling: 84,
        defending: 75,
        physical: 85,
      },
      {
        name: "Federico Valverde",
        position: "Midfielder",
        overall: 86,
        pace: 88,
        shooting: 80,
        passing: 82,
        dribbling: 83,
        defending: 78,
        physical: 85,
      },
      {
        name: "Vinícius Jr.",
        position: "Forward",
        overall: 89,
        pace: 95,
        shooting: 84,
        passing: 78,
        dribbling: 92,
        defending: 30,
        physical: 70,
      },
      {
        name: "Rodrygo",
        position: "Forward",
        overall: 85,
        pace: 88,
        shooting: 80,
        passing: 75,
        dribbling: 86,
        defending: 35,
        physical: 68,
      },
      {
        name: "Joselu",
        position: "Forward",
        overall: 82,
        pace: 72,
        shooting: 83,
        passing: 68,
        dribbling: 70,
        defending: 40,
        physical: 78,
      },
      {
        name: "Brahim Díaz",
        position: "Forward",
        overall: 80,
        pace: 85,
        shooting: 75,
        passing: 72,
        dribbling: 84,
        defending: 35,
        physical: 65,
      },
      {
        name: "Arda Güler",
        position: "Forward",
        overall: 78,
        pace: 82,
        shooting: 76,
        passing: 74,
        dribbling: 85,
        defending: 30,
        physical: 60,
      },
    ];

    response.json({data: {players: madridPlayers}});
  }
);
