import * as functions from "firebase-functions";

export const getBarcelonaPlayers = functions.https.onRequest(
  (request, response) => {
    const barcelonaPlayers = [
      {
        name: "Marc-André ter Stegen",
        position: "Goalkeeper",
        overall: 89,
        pace: 55,
        shooting: 40,
        passing: 65,
        dribbling: 60,
        defending: 45,
        physical: 60,
      },
      {
        name: "Iñaki Peña",
        position: "Goalkeeper",
        overall: 82,
        pace: 50,
        shooting: 35,
        passing: 55,
        dribbling: 50,
        defending: 40,
        physical: 55,
      },
      {
        name: "Wojciech Szczęsny",
        position: "Goalkeeper",
        overall: 85,
        pace: 52,
        shooting: 38,
        passing: 58,
        dribbling: 55,
        defending: 42,
        physical: 58,
      },
      {
        name: "Pau Cubarsí",
        position: "Defender",
        overall: 78,
        pace: 70,
        shooting: 45,
        passing: 65,
        dribbling: 60,
        defending: 75,
        physical: 70,
      },
      {
        name: "Alejandro Balde",
        position: "Defender",
        overall: 80,
        pace: 75,
        shooting: 48,
        passing: 68,
        dribbling: 65,
        defending: 78,
        physical: 72,
      },
      {
        name: "Ronald Araujo",
        position: "Defender",
        overall: 86,
        pace: 65,
        shooting: 50,
        passing: 60,
        dribbling: 55,
        defending: 88,
        physical: 89,
      },
      {
        name: "Iñigo Martínez",
        position: "Defender",
        overall: 84,
        pace: 60,
        shooting: 45,
        passing: 70,
        dribbling: 60,
        defending: 85,
        physical: 80,
      },
      {
        name: "Andreas Christensen",
        position: "Defender",
        overall: 83,
        pace: 62,
        shooting: 40,
        passing: 72,
        dribbling: 60,
        defending: 84,
        physical: 82,
      },
      {
        name: "Jules Koundé",
        position: "Defender",
        overall: 85,
        pace: 70,
        shooting: 45,
        passing: 70,
        dribbling: 65,
        defending: 86,
        physical: 84,
      },
      {
        name: "Eric García",
        position: "Defender",
        overall: 81,
        pace: 65,
        shooting: 40,
        passing: 70,
        dribbling: 65,
        defending: 80,
        physical: 75,
      },
      {
        name: "Gerard Martín",
        position: "Defender",
        overall: 79,
        pace: 68,
        shooting: 42,
        passing: 65,
        dribbling: 60,
        defending: 78,
        physical: 75,
      },
      {
        name: "Frenkie de Jong",
        position: "Midfielder",
        overall: 87,
        pace: 72,
        shooting: 75,
        passing: 88,
        dribbling: 86,
        defending: 70,
        physical: 75,
      },
      {
        name: "Pedri",
        position: "Midfielder",
        overall: 88,
        pace: 75,
        shooting: 80,
        passing: 90,
        dribbling: 92,
        defending: 65,
        physical: 70,
      },
      {
        name: "Gavi",
        position: "Midfielder",
        overall: 85,
        pace: 78,
        shooting: 70,
        passing: 85,
        dribbling: 87,
        defending: 68,
        physical: 72,
      },
      {
        name: "Casadó",
        position: "Midfielder",
        overall: 80,
        pace: 70,
        shooting: 65,
        passing: 78,
        dribbling: 75,
        defending: 70,
        physical: 72,
      },
      {
        name: "Darvich",
        position: "Midfielder",
        overall: 79,
        pace: 72,
        shooting: 60,
        passing: 75,
        dribbling: 78,
        defending: 68,
        physical: 70,
      },
      {
        name: "Torre",
        position: "Midfielder",
        overall: 81,
        pace: 75,
        shooting: 68,
        passing: 78,
        dribbling: 80,
        defending: 65,
        physical: 72,
      },
      {
        name: "Ansu Fati",
        position: "Forward",
        overall: 84,
        pace: 89,
        shooting: 82,
        passing: 75,
        dribbling: 86,
        defending: 35,
        physical: 65,
      },
      {
        name: "Fermín López",
        position: "Forward",
        overall: 82,
        pace: 85,
        shooting: 80,
        passing: 70,
        dribbling: 82,
        defending: 30,
        physical: 68,
      },
      {
        name: "Ferran Torres",
        position: "Forward",
        overall: 82,
        pace: 85,
        shooting: 80,
        passing: 75,
        dribbling: 83,
        defending: 30,
        physical: 68,
      },
      {
        name: "Robert Lewandowski",
        position: "Forward",
        overall: 91,
        pace: 78,
        shooting: 93,
        passing: 78,
        dribbling: 85,
        defending: 45,
        physical: 80,
      },
      {
        name: "Olmo",
        position: "Forward",
        overall: 83,
        pace: 82,
        shooting: 80,
        passing: 75,
        dribbling: 84,
        defending: 30,
        physical: 69,
      },
      {
        name: "Pau Victor",
        position: "Forward",
        overall: 81,
        pace: 84,
        shooting: 78,
        passing: 70,
        dribbling: 82,
        defending: 28,
        physical: 67,
      },
      {
        name: "Raphinha",
        position: "Forward",
        overall: 84,
        pace: 86,
        shooting: 82,
        passing: 75,
        dribbling: 85,
        defending: 32,
        physical: 70,
      },
      {
        name: "Yamal",
        position: "Forward",
        overall: 80,
        pace: 88,
        shooting: 78,
        passing: 72,
        dribbling: 84,
        defending: 30,
        physical: 65,
      },
    ];

    response.send(barcelonaPlayers);
  }
);
